
name: CI-SFTP
on:
  push:
    branches: [ main ]
jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SSH_USER }}
          server: ${{ secrets.SERVER_IP }}
          port: 22 
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}

          local_path: ./* 
          remote_path: /var/www/cat-wiki-be
          
          # sftp args
          args: '-o ConnectTimeout=5'